version: '3.8'

services:
  backend:
    build:
      context: https://github.com/rickydg/SeeCash.git#main
      dockerfile: backend/Dockerfile
    image: seecash-backend:latest
    ports:
      - "${BACKEND_PORT:-8089}:8080"  # Use port 8089 by default or set BACKEND_PORT env variable
    volumes:
      - /mnt/user/appdata/seecash/backend:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_PATH=data/budget.db
      - LOG_LEVEL=info
      - MAX_DB_SIZE_MB=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    labels:
      - "com.unraid.name=SeeCash-Backend"
      - "com.unraid.description=SeeCash Budget Application Backend"

  frontend:
    build:
      context: https://github.com/rickydg/SeeCash.git#main
      dockerfile: frontend/Dockerfile
    image: seecash-frontend:latest
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 300M
    labels:
      - "com.unraid.name=SeeCash-Frontend"
      - "com.unraid.description=SeeCash Budget Application Frontend"
    environment:
      - API_URL=http://backend:8080  # Point to the service name and internal port

volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/user/appdata/seecash/backend
      o: bind